dist: xenial
language: python
sudo: false
python:
  - '3.5'

install:
  - pip3 install -r requirements.txt --upgrade
  - pip3 install -r user_requirements.txt --upgrade
  - pip3 install pytest-cov codecov python-coveralls
  - pip3 uninstall pytest-capturelog || true
before_script:
  - git config user.name SmokeDetector
  - git config user.email "smokey@erwaysoftware.com"
  - git config remote.origin.fetch "+refs/heads/master:refs/remotes/origin/master"
  - git config --add remote.origin.fetch "+refs/heads/deploy:refs/remotes/origin/deploy"
  - git fetch origin --depth=3
  - git checkout --track origin/deploy
  - git checkout master
script:
  - flake8 --config=tox_tests.ini ./test/
  - flake8 --config=tox_classes.ini ./classes/
  - flake8 ./
  - python3 -W default::Warning -m pytest --cov=chatcommunicate --cov=findspam --cov=globalvars --cov=spamhandling --cov=datahandling --cov=chatcommands --cov=helpers test

branches:
  only:
    - master
cache:
  directories:
    - $HOME/virtualenv/python3.5.*
    - $HOME/.cache/pip
before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log
  - rm -rf $HOME/.cache/pip/http
after_success:
  - coveralls
